name: 'Build Watermark'
description: 'Create professional CI/CD watermarks for your projects effortlessly'
inputs:
  format:
    description: 'Format of the watermark'
    required: true
    default: 'REF.SHA7 DATE'
  auto-version:
    description: 'Define the flavour of the project to read the version from'
    required: false
    default: 'npm'
  version:
    description: 'Manually set the current version in semver format'
    required: false
  empty-value:
    description: 'Placeholder for any missing value in the watermark format'
    required: true
    default: '?'
outputs:
  watermark:
    description: 'The produced watermark'
  REF:
    description: 'The fully-formed ref of the branch or tag that triggered the workflow run'
  BRANCH:
    description: 'The branch that triggered the workflow run'
  BRANCH_FILE:
    description: 'The branch name in a filename-safe format'
  BRANCH_PREFIX:
    description: 'The portion of the branch name before the first slash, if any'
  TAGS:
    description: 'The tag that triggered the workflow run'
  SHA:
    description: 'The hash of the commit that is being processed'
  SHA8:
    description: 'The first 8 digits of the commit hash'
  SHA7:
    description: 'The first 7 digits of the commit hash'
  RUN:
    description: 'The incremental id of the GitHub action run'
  VERSION:
    description: 'The current project version'
  MAYOR:
    description: 'The mayor component of the project version'
  MINOR:
    description: 'The minor component of the project version'
  PATCH:
    description: 'The patch component of the project version'
  DATE:
    description: 'The current date'
  DATETIME:
    description: 'The current date and time'
  YYYY:
    description: 'The current year as a 4-digit string'
  YY:
    description: 'The current year as a 2-digit string'
  MM:
    description: 'The current month as a 2-digit string'
  DD:
    description: 'The current day of the month as a 2-digit string'
  HH:
    description: 'The current hour as a 2-digit string'
  mm:
    description: 'The current minute as a 2-digit string'
  ss:
    description: 'The current second as a 2-digit string'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'hash'
  color: 'orange'
